package me.iyansiwik.zelda1;

public class Zelda extends Game {

	public Zelda(double scale) {
		super(scale);
	}
	
	public void init() {
		Audio aud_overworld = new Audio("audio/Overworld", 1f, true);
		
		Tileset overworld1 = new Tileset("tilesets/overworld1", 16);
		Tile stairs1 = new Tile(overworld1, 0, 0);
		Tile stone1 = new Tile(overworld1, 1, 0, false);
		Tile ground1 = new Tile(overworld1, 2, 0);
		Tile tree_ul1 = new Tile(overworld1, 3, 0, false);
		Tile tree_u1 = new Tile(overworld1, 4, 0, false);
		Tile tree_ur1 = new Tile(overworld1, 5, 0, true, false, false, true);
		Tile ladder1 = new Tile(overworld1, 0, 1);
		Tile tree1 = new Tile(overworld1, 1, 1, false);
		Tile armos1 = new Tile(overworld1, 2, 1, false);
		Tile tree_dl1 = new Tile(overworld1, 3, 1, false, true, true, false);
		Tile cave1 = new Tile(overworld1, 4, 1, false, false, true, true);
		Tile tree_dr1 = new Tile(overworld1, 5, 1, false);
		Tile rock_ul1 = new Tile(overworld1, 0, 2, false, true, false, false);
		Tile rock_u1 = new Tile(overworld1, 1, 2, false);
		Tile rock_ur1 = new Tile(overworld1, 2, 2, true, false, false, false);
		Tile statue_ul1 = new Tile(overworld1, 3, 2, false, true, false, false);
		Tile statue_u1 = new Tile(overworld1, 4, 2, false);
		Tile statue_ur1 = new Tile(overworld1, 5, 2, true, false, false, false);
		Tile rock_dl1 = new Tile(overworld1, 0, 3, false, false, true, false);
		Tile rock1 = new Tile(overworld1, 1, 3, false);
		Tile rock_dr1 = new Tile(overworld1, 2, 3, false, false, false, true);
		Tile statue_dl1 = new Tile(overworld1, 3, 3, false);
		Tile sand1 = new Tile(overworld1, 4, 3);
		Tile statue_dr1 = new Tile(overworld1, 5, 3, false);
		Tile water_ul1 = new Tile(overworld1, 0, 4, false);
		Tile water_u1 = new Tile(overworld1, 1, 4, false);
		Tile water_ur1 = new Tile(overworld1, 2, 4, false);
		Tile dry_ul1 = new Tile(overworld1, 3, 4);
		Tile dry_u1 = new Tile(overworld1, 4, 4);
		Tile dry_ur1 = new Tile(overworld1, 5, 4);
		Tile water_l1 = new Tile(overworld1, 0, 5, false);
		Tile water1 = new Tile(overworld1, 1, 5, false);
		Tile water_r1 = new Tile(overworld1, 2, 5, false);
		Tile dry_l1 = new Tile(overworld1, 3, 5);
		Tile dry1 = new Tile(overworld1, 4, 5);
		Tile dry_r1 = new Tile(overworld1, 5, 5);
		Tile water_dl1 = new Tile(overworld1, 0, 6, false);
		Tile water_d1 = new Tile(overworld1, 1, 6, false);
		Tile water_dr1 = new Tile(overworld1, 2, 6, false);
		Tile dry_dl1 = new Tile(overworld1, 3, 6);
		Tile dry_d1 = new Tile(overworld1, 4, 6);
		Tile dry_dr1 = new Tile(overworld1, 5, 6);
		Tile island_ul1 = new Tile(overworld1, 0, 7, true, false, true, true);
		Tile island_ur1 = new Tile(overworld1, 1, 7);
		Tile island_dl1 = new Tile(overworld1, 2, 7);
		Tile island_dr1 = new Tile(overworld1, 3, 7);
		Tile waterfall1 = new Tile(overworld1, 4, 7, false, false, true, true);
		Tile dock1 = new Tile(overworld1, 5, 7);
		
		Tileset overworld2 = new Tileset("tilesets/overworld2", 16);
		Tile stairs2 = new Tile(overworld2, 0, 0);
		Tile stone2 = new Tile(overworld2, 1, 0, false);
		Tile ground2 = new Tile(overworld2, 2, 0);
		Tile tree_ul2 = new Tile(overworld2, 3, 0, false);
		Tile tree_u2 = new Tile(overworld2, 4, 0, false);
		Tile tree_ur2 = new Tile(overworld2, 5, 0, true, false, false, true);
		Tile ladder2 = new Tile(overworld2, 0, 1);
		Tile tree2 = new Tile(overworld2, 1, 1, false);
		Tile armos2 = new Tile(overworld2, 2, 1, false);
		Tile tree_dl2 = new Tile(overworld2, 3, 1, false, true, true, false);
		Tile cave2 = new Tile(overworld2, 4, 1, false, false, true, true);
		Tile tree_dr2 = new Tile(overworld2, 5, 1, false);
		Tile rock_ul2 = new Tile(overworld2, 0, 2, false, true, false, false);
		Tile rock_u2 = new Tile(overworld2, 1, 2, false);
		Tile rock_ur2 = new Tile(overworld2, 2, 2, true, false, false, false);
		Tile statue_ul2 = new Tile(overworld2, 3, 2, false, true, false, false);
		Tile statue_u2 = new Tile(overworld2, 4, 2, false);
		Tile statue_ur2 = new Tile(overworld2, 5, 2, true, false, false, false);
		Tile rock_dl2 = new Tile(overworld2, 0, 3, false, false, true, false);
		Tile rock2 = new Tile(overworld2, 1, 3, false);
		Tile rock2_walkthrough = new Tile(overworld2, 1, 3);
		Tile rock_dr2 = new Tile(overworld2, 2, 3, false, false, false, true);
		Tile statue_dl2 = new Tile(overworld2, 3, 3, false);
		Tile sand2 = new Tile(overworld2, 4, 3);
		Tile statue_dr2 = new Tile(overworld2, 5, 3, false);
		Tile water_ul2 = new Tile(overworld2, 0, 4, false);
		Tile water_u2 = new Tile(overworld2, 1, 4, false);
		Tile water_ur2 = new Tile(overworld2, 2, 4, false);
		Tile dry_ul2 = new Tile(overworld2, 3, 4);
		Tile dry_u2 = new Tile(overworld2, 4, 4);
		Tile dry_ur2 = new Tile(overworld2, 5, 4);
		Tile water_l2 = new Tile(overworld2, 0, 5, false);
		Tile water2 = new Tile(overworld2, 1, 5, false);
		Tile water_r2 = new Tile(overworld2, 2, 5, false);
		Tile dry_l2 = new Tile(overworld2, 3, 5);
		Tile dry2 = new Tile(overworld2, 4, 5);
		Tile dry_r2 = new Tile(overworld2, 5, 5);
		Tile water_dl2 = new Tile(overworld2, 0, 6, false);
		Tile water_d2 = new Tile(overworld2, 1, 6, false);
		Tile water_dr2 = new Tile(overworld2, 2, 6, false);
		Tile dry_dl2 = new Tile(overworld2, 3, 6);
		Tile dry_d2 = new Tile(overworld2, 4, 6);
		Tile dry_dr2 = new Tile(overworld2, 5, 6);
		Tile island_ul2 = new Tile(overworld2, 0, 7, true, false, true, true);
		Tile island_ur2 = new Tile(overworld2, 1, 7);
		Tile island_dl2 = new Tile(overworld2, 2, 7);
		Tile island_dr2 = new Tile(overworld2, 3, 7);
		Tile waterfall2 = new Tile(overworld2, 4, 7, false, false, true, true);
		Tile dock2 = new Tile(overworld2, 5, 7);
		
		Tileset overworld3 = new Tileset("tilesets/overworld3", 16);
		Tile stairs3 = new Tile(overworld3, 0, 0);
		Tile grave3 = new Tile(overworld3, 1, 0, false);
		Tile ground3 = new Tile(overworld3, 2, 0);
		Tile tree_ul3 = new Tile(overworld3, 3, 0, false);
		Tile tree_u3 = new Tile(overworld3, 4, 0, false);
		Tile tree_ur3 = new Tile(overworld3, 5, 0, true, false, false, true);
		Tile ladder3 = new Tile(overworld3, 0, 1);
		Tile tree3 = new Tile(overworld3, 1, 1, false);
		Tile armos3 = new Tile(overworld3, 2, 1, false);
		Tile tree_dl3 = new Tile(overworld3, 3, 1, false, true, true, false);
		Tile cave3 = new Tile(overworld3, 4, 1, false, false, true, true);
		Tile tree_dr3 = new Tile(overworld3, 5, 1, false);
		Tile rock_ul3 = new Tile(overworld3, 0, 1, false, true, false, false);
		Tile rock_u3 = new Tile(overworld3, 1, 2, false);
		Tile rock_ur3 = new Tile(overworld3, 2, 2, true, false, false, false);
		Tile statue_ul3 = new Tile(overworld3, 3, 2, false, true, false, false);
		Tile statue_u3 = new Tile(overworld3, 4, 2, false);
		Tile statue_ur3 = new Tile(overworld3, 5, 2, true, false, false, false);
		Tile rock_dl3 = new Tile(overworld3, 0, 3, false, false, true, false);
		Tile rock3 = new Tile(overworld3, 1, 3, false);
		Tile rock_dr3 = new Tile(overworld3, 2, 3, false, false, false, true);
		Tile statue_dl3 = new Tile(overworld3, 3, 3, false);
		Tile sand3 = new Tile(overworld3, 4, 3);
		Tile statue_dr3 = new Tile(overworld3, 5, 3, false);
		Tile water_ul3 = new Tile(overworld3, 0, 4, false);
		Tile water_u3 = new Tile(overworld3, 1, 4, false);
		Tile water_ur3 = new Tile(overworld3, 2, 4, false);
		Tile dry_ul3 = new Tile(overworld3, 3, 4);
		Tile dry_u3 = new Tile(overworld3, 4, 4);
		Tile dry_ur3 = new Tile(overworld3, 5, 4);
		Tile water_l3 = new Tile(overworld3, 0, 5, false);
		Tile water3 = new Tile(overworld3, 1, 5, false);
		Tile water_r3 = new Tile(overworld3, 2, 5, false);
		Tile dry_l3 = new Tile(overworld3, 3, 5);
		Tile dry3 = new Tile(overworld3, 4, 5);
		Tile dry_r3 = new Tile(overworld3, 5, 5);
		Tile water_dl3 = new Tile(overworld3, 0, 6, false);
		Tile water_d3 = new Tile(overworld3, 1, 6, false);
		Tile water_dr3 = new Tile(overworld3, 2, 6, false);
		Tile dry_dl3 = new Tile(overworld3, 3, 6);
		Tile dry_d3 = new Tile(overworld3, 4, 6);
		Tile dry_dr3 = new Tile(overworld3, 5, 6);
		Tile island_ul3 = new Tile(overworld3, 0, 7, true, false, true, true);
		Tile island_ur3 = new Tile(overworld3, 1, 7);
		Tile island_dl3 = new Tile(overworld3, 2, 7);
		Tile island_dr3 = new Tile(overworld3, 3, 7);
		Tile waterfall3 = new Tile(overworld3, 4, 7, false, false, true, true);
		Tile dock3 = new Tile(overworld3, 5, 7);
		
		Screen A0 = new Screen(aud_overworld);
		A0.load("screens/A0", new Tile[] {ground2, rock2, rock_u2, ladder2});
		Screen A1 = new Screen(aud_overworld);
		A1.load("screens/A1", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ul2, rock_ur2, ladder2, cave2});
		Screen A2 = new Screen(aud_overworld);
		A2.load("screens/A2", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, ladder2});
		Screen A3 = new Screen(aud_overworld);
		A3.load("screens/A3", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ul2, ladder2, cave2});
		Screen A4 = new Screen(aud_overworld);
		A4.load("screens/A4", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, cave2});
		Screen A5 = new Screen(aud_overworld);
		A5.load("screens/A5", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ul2, rock_ur2, cave2});
		Screen A6 = new Screen(aud_overworld);
		A6.load("screens/A6", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2});
		Screen A7 = new Screen(aud_overworld);
		A7.load("screens/A7", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, ladder2, cave2});
		Screen A8 = new Screen(aud_overworld);
		A8.load("screens/A8", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2});
		Screen A9 = new Screen(aud_overworld);
		A9.load("screens/A9", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, stone2});
		Screen A10 = new Screen(aud_overworld);
		A10.load("screens/A10", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, ladder2, cave2, water_ul2, water_u2, water_ur2, water_l2, water2, water_r2, water_dl2, water_d2, water_dr2, island_ur2, island_ul2});
		Screen A11 = new Screen(aud_overworld);
		A11.load("screens/A11", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, ladder2, cave2, armos2, statue_ul2, statue_u2, statue_ur2, statue_dl2, statue_dr2});
		Screen A12 = new Screen(aud_overworld);
		A12.load("screens/A12", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, ladder2, cave2});
		Screen A13 = new Screen(aud_overworld);
		A13.load("screens/A13", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, ladder2, cave2});
		Screen A14 = new Screen(aud_overworld);
		A14.load("screens/A14", new Tile[] {ground2, rock2, water2, ladder2, cave2});
		Screen A15 = new Screen(aud_overworld);
		A15.load("screens/A15", new Tile[] {ground2, rock2, rock_u2, water2, statue_ul2, statue_ur2, statue_dl2, statue_dr2, statue_u2, cave2, ladder2});
		
		Screen B0 = new Screen(aud_overworld);
		B0.load("screens/B0", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_ur2, stone2, tree_ul2, tree_ur2, tree_dl2, tree_dr2, ladder2, cave2});
		Screen B1 = new Screen(aud_overworld);
		B1.load("screens/B1", new Tile[] {ground2, rock2, rock_u2, rock_dl2, rock_ul2, tree_ul2, tree_ur2, tree_dl2, tree_dr2, stone2, ladder2});
		Screen B2 = new Screen(aud_overworld);
		B2.load("screens/B2", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_ur2, tree_ul2, tree_ur2, tree_dl2, tree_dr2, cave2, ladder2});
		Screen B3 = new Screen(aud_overworld);
		B3.load("screens/B3", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, ladder2, cave2, tree_ur2, tree_dr2});
		Screen B4 = new Screen(aud_overworld);
		B4.load("screens/B4", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, ladder2, cave2, armos2});
		Screen B5 = new Screen(aud_overworld);
		B5.load("screens/B5", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, ladder2});
		Screen B6 = new Screen(aud_overworld);
		B6.load("screens/B6", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, cave2});
		Screen B7 = new Screen(aud_overworld);
		B7.load("screens/B7", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, ladder2, water_ul2, water_d2, water2});
		Screen B8 = new Screen(aud_overworld);
		B8.load("screens/B8", new Tile[] {ground2, rock2, rock_u2, water_d2});
		Screen B9 = new Screen(aud_overworld);
		B9.load("screens/B9", new Tile[] {ground2, rock2, rock_u2, water_d2});
		Screen B10 = new Screen(aud_overworld);
		B10.load("screens/B10", new Tile[] {ground2, rock2, rock_u2, water_d2, waterfall2, ladder2});
		Screen B11 = new Screen(aud_overworld);
		B11.load("screens/B11", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, ladder2, stone2});
		Screen B12 = new Screen(aud_overworld);
		B12.load("screens/B12", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_ur2, ladder2, armos2});
		Screen B13 = new Screen(aud_overworld);
		B13.load("screens/B13", new Tile[] {ground2, rock2, rock_u2, rock_dr2, rock_dl2, rock_ur2, rock_ul2, ladder2, stone2, water_ul2, water_u2, water_l2, water2});
		Screen B14 = new Screen(aud_overworld);
		B14.load("screens/B14", new Tile[] {ground2, rock2, rock_u2, rock_dr2, water_u2, water2, cave2, ladder2});
		Screen B15 = new Screen(aud_overworld);
		B15.load("screens/B15", new Tile[] {ground2, rock2, rock_u2, rock2_walkthrough, water2, tree_ul1, tree_ur1, tree_u1, tree_dl1, tree_dr1, cave2});
		
		Screen C0 = new Screen(aud_overworld);
		C0.load("screens/C0", new Tile[] {ground3, rock3, rock_u3, rock_dr3, grave3});
		Screen C1 = new Screen(aud_overworld);
		C1.load("screens/C1", new Tile[] {ground3, rock3, rock_u3, tree3, grave3});
		Screen C2 = new Screen(aud_overworld);
		C2.load("screens/C2", new Tile[] {ground3, rock2, rock_u2, statue_ul3, statue_u3, statue_ur3, statue_dl3, cave3, statue_dr3, armos3, ladder2});
		Screen C3 = new Screen(aud_overworld);
//		C3.load("screens/C3", new Tile[] {});
		Screen C4 = new Screen(aud_overworld);
//		C4.load("screens/C4", new Tile[] {});
		Screen C5 = new Screen(aud_overworld);
//		C5.load("screens/C5", new Tile[] {});
		Screen C6 = new Screen(aud_overworld);
//		C6.load("screens/C6", new Tile[] {});
		Screen C7 = new Screen(aud_overworld);
//		C7.load("screens/C7", new Tile[] {});
		Screen C8 = new Screen(aud_overworld);
//		C8.load("screens/C8", new Tile[] {});
		Screen C9 = new Screen(aud_overworld);
//		C9.load("screens/C9", new Tile[] {});
		Screen C10 = new Screen(aud_overworld);
//		C10.load("screens/C10", new Tile[] {});
		Screen C11 = new Screen(aud_overworld);
//		C11.load("screens/C11", new Tile[] {});
		Screen C12 = new Screen(aud_overworld);
//		C12.load("screens/C12", new Tile[] {});
		Screen C13 = new Screen(aud_overworld);
//		C13.load("screens/C13", new Tile[] {});
		Screen C14 = new Screen(aud_overworld);
//		C14.load("screens/C14", new Tile[] {});
		Screen C15 = new Screen(aud_overworld);
//		C15.load("screens/C15", new Tile[] {});
		
//		setScreen(C2);
		
		Screen D0 = new Screen(aud_overworld);
//		D0.load("screens/D0", new Tile[] {});
		Screen D1 = new Screen(aud_overworld);
//		D1.load("screens/D1", new Tile[] {});
		Screen D2 = new Screen(aud_overworld);
//		D2.load("screens/C1", new Tile[] {});
		Screen D3 = new Screen(aud_overworld);
//		D3.load("screens/D3", new Tile[] {});
		Screen D4 = new Screen(aud_overworld);
//		D4.load("screens/D4", new Tile[] {});
		Screen D5 = new Screen(aud_overworld);
//		D5.load("screens/D5", new Tile[] {});
		Screen D6 = new Screen(aud_overworld);
//		D6.load("screens/D6", new Tile[] {});
		Screen D7 = new Screen(aud_overworld);
//		D7.load("screens/D7", new Tile[] {});
		Screen D8 = new Screen(aud_overworld);
//		D8.load("screens/D8", new Tile[] {});
		Screen D9 = new Screen(aud_overworld);
//		D9.load("screens/D9", new Tile[] {});
		Screen D10 = new Screen(aud_overworld);
//		D10.load("screens/D10", new Tile[] {});
		Screen D11 = new Screen(aud_overworld);
//		D11.load("screens/D11", new Tile[] {});
		Screen D12 = new Screen(aud_overworld);
//		D12.load("screens/D12", new Tile[] {});
		Screen D13 = new Screen(aud_overworld);
//		D13.load("screens/D13", new Tile[] {});
		Screen D14 = new Screen(aud_overworld);
//		D14.load("screens/D14", new Tile[] {});
		Screen D15 = new Screen(aud_overworld);
//		D15.load("screens/D15", new Tile[] {});
		
		Screen E0 = new Screen(aud_overworld);
//		E0.load("screens/E0", new Tile[] {});
		Screen E1 = new Screen(aud_overworld);
//		E1.load("screens/E1", new Tile[] {});
		Screen E2 = new Screen(aud_overworld);
//		E2.load("screens/E2", new Tile[] {});
		Screen E3 = new Screen(aud_overworld);
//		E3.load("screens/E3", new Tile[] {});
		Screen E4 = new Screen(aud_overworld);
//		E4.load("screens/E4", new Tile[] {});
		Screen E5 = new Screen(aud_overworld);
//		E5.load("screens/E5", new Tile[] {});
		Screen E6 = new Screen(aud_overworld);
//		E6.load("screens/E6", new Tile[] {});
		Screen E7 = new Screen(aud_overworld);
//		E7.load("screens/E7", new Tile[] {});
		Screen E8 = new Screen(aud_overworld);
//		E8.load("screens/E8", new Tile[] {});
		Screen E9 = new Screen(aud_overworld);
//		E9.load("screens/E9", new Tile[] {});
		Screen E10 = new Screen(aud_overworld);
//		E10.load("screens/E10", new Tile[] {});
		Screen E11 = new Screen(aud_overworld);
//		E11.load("screens/E11", new Tile[] {});
		Screen E12 = new Screen(aud_overworld);
//		E12.load("screens/E12", new Tile[] {});
		Screen E13 = new Screen(aud_overworld);
//		E13.load("screens/E13", new Tile[] {});
		Screen E14 = new Screen(aud_overworld);
//		E14.load("screens/E14", new Tile[] {});
		Screen E15 = new Screen(aud_overworld);
//		E15.load("screens/E15", new Tile[] {});
		
		Screen F0 = new Screen(aud_overworld);
//		F0.load("screens/F0", new Tile[] {});
		Screen F1 = new Screen(aud_overworld);
//		F1.load("screens/F1", new Tile[] {});
		Screen F2 = new Screen(aud_overworld);
//		F2.load("screens/F2", new Tile[] {});
		Screen F3 = new Screen(aud_overworld);
//		F3.load("screens/F3", new Tile[] {});
		Screen F4 = new Screen(aud_overworld);
//		F4.load("screens/F4", new Tile[] {});
		Screen F5 = new Screen(aud_overworld);
//		F5.load("screens/F5", new Tile[] {});
		Screen F6 = new Screen(aud_overworld);
//		F6.load("screens/F6", new Tile[] {});
		Screen F7 = new Screen(aud_overworld);
//		F7.load("screens/F7", new Tile[] {});
		Screen F8 = new Screen(aud_overworld);
//		F8.load("screens/F8", new Tile[] {});
		Screen F9 = new Screen(aud_overworld);
//		F9.load("screens/F9", new Tile[] {});
		Screen F10 = new Screen(aud_overworld);
//		F10.load("screens/F10", new Tile[] {});
		Screen F11 = new Screen(aud_overworld);
//		F11.load("screens/F11", new Tile[] {});
		Screen F12 = new Screen(aud_overworld);
//		F12.load("screens/F12", new Tile[] {});
		Screen F13 = new Screen(aud_overworld);
//		F13.load("screens/F13", new Tile[] {});
		Screen F14 = new Screen(aud_overworld);
//		F14.load("screens/F14", new Tile[] {});
		Screen F15 = new Screen(aud_overworld);
//		F15.load("screens/F15", new Tile[] {});
		
		Screen G0 = new Screen(aud_overworld);
//		G0.load("screens/G0", new Tile[] {});
		Screen G1 = new Screen(aud_overworld);
//		G1.load("screens/G1", new Tile[] {});
		Screen G2 = new Screen(aud_overworld);
//		G2.load("screens/G2", new Tile[] {});
		Screen G3 = new Screen(aud_overworld);
//		G3.load("screens/G3", new Tile[] {});
		Screen G4 = new Screen(aud_overworld);
//		G4.load("screens/G4", new Tile[] {});
		Screen G5 = new Screen(aud_overworld);
//		G5.load("screens/G5", new Tile[] {});
		Screen G6 = new Screen(aud_overworld);
//		G6.load("screens/G6", new Tile[] {});
		Screen G7 = new Screen(aud_overworld);
//		G7.load("screens/G7", new Tile[] {});
		Screen G8 = new Screen(aud_overworld);
//		G8.load("screens/G8", new Tile[] {});
		Screen G9 = new Screen(aud_overworld);
//		G9.load("screens/G9", new Tile[] {});
		Screen G10 = new Screen(aud_overworld);
//		G10.load("screens/G10", new Tile[] {});
		Screen G11 = new Screen(aud_overworld);
//		G11.load("screens/G11", new Tile[] {});
		Screen G12 = new Screen(aud_overworld);
//		G12.load("screens/G12", new Tile[] {});
		Screen G13 = new Screen(aud_overworld);
//		G13.load("screens/G13", new Tile[] {});
		Screen G14 = new Screen(aud_overworld);
//		G14.load("screens/G14", new Tile[] {});
		Screen G15 = new Screen(aud_overworld);
//		G15.load("screens/G15", new Tile[] {});
		
		Screen H0 = new Screen(aud_overworld);
//		H0.load("screens/H0", new Tile[] {});
		Screen H1 = new Screen(aud_overworld);
//		H1.load("screens/H1", new Tile[] {});
		Screen H2 = new Screen(aud_overworld);
//		H2.load("screens/H2", new Tile[] {});
		Screen H3 = new Screen(aud_overworld);
//		H3.load("screens/H3", new Tile[] {});
		Screen H4 = new Screen(aud_overworld);
//		H4.load("screens/H4", new Tile[] {});
		Screen H5 = new Screen(aud_overworld);
//		H5.load("screens/H5", new Tile[] {});
		Screen H6 = new Screen(aud_overworld);
//		H6.load("screens/H6", new Tile[] {});
		Screen H7 = new Screen(aud_overworld); //START SCREEN
		H7.load("screens/H7", new Tile[] {ground1, rock1, rock_u1, rock_dr1, rock_dl1, rock_ur1, cave1});
		Screen H8 = new Screen(aud_overworld);
//		H8.load("screens/H8", new Tile[] {});
		Screen H9 = new Screen(aud_overworld);
//		H9.load("screens/H9", new Tile[] {});
		Screen H10 = new Screen(aud_overworld);
//		H10.load("screens/H10", new Tile[] {});
		Screen H11 = new Screen(aud_overworld);
//		H11.load("screens/H11", new Tile[] {});
		Screen H12 = new Screen(aud_overworld);
//		H12.load("screens/H12", new Tile[] {});
		Screen H13 = new Screen(aud_overworld);
//		H13.load("screens/H13", new Tile[] {});
		Screen H14 = new Screen(aud_overworld);
//		H14.load("screens/H14", new Tile[] {});
		Screen H15 = new Screen(aud_overworld);
//		H15.load("screens/H15", new Tile[] {});
		
		setScreen(H7);
	}
}
